# Sample taken from puppet-redmine

redmine:
  # Ubuntu 22.04 x86_64
  ami_id: ami-0faab6bdbac9486fb

  # Value of the "Name" tag for the instance. In other words, the human-readable
  # name of the EC2 instance that will be created.
  instance_name: redmine

  # Instance type
  instance_type: t3.medium

  # SSH user that has passwordless sudo privileges. Typically the default user of
  # the AMI provider.
  login_user: ubuntu

  # Copy these files. Note that paths are evaluated from the ansible-aws-provision
  # subdirectory, so remember to add a "..".
  #
  # Try to cherry-pick what you transfer: the playbook uses ansible.builtin.copy
  # which is very slow when transfering lots of data (e.g. .git directories).
  #
  files:
    "../data": "/tmp/redmine"
    "../hiera.yaml": "/tmp/redmine"
    "../manifests": "/tmp/redmine"
    "../templates": "/tmp/redmine"
    "../Puppetfile": "/tmp/redmine"
    "../vagrant": "/tmp/redmine"

  # Run these arbitrary provisioning commands on the EC2 instance.
  commands:
    - "/tmp/redmine/vagrant/common.sh"
    - "/opt/puppetlabs/bin/puppet apply /tmp/redmine/vagrant/redmine.pp --modulepath=/tmp/redmine/modules"
